# This is a basic workflow that is manually triggered

name: archbuild

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Start building'
        # Default value if no value is explicitly provided
        default: 'default'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "archbuild"
  baseline_iso:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
   # - name: download-profile
     # run: |
       # sudo pacman -Syu --noconfirm
       # git clone https://github.com/justaguy31/archiso-lfs.git
       # cd archiso-lfs/baseline
    - name: build-iso
      run: |
        sudo pacman -Syu --noconfirm
        mkarchiso -v .
